package com.aashik.music.service

import android.app.Notification
import android.content.pm.PackageManager
import android.service.notification.NotificationListenerService
import android.service.notification.StatusBarNotification
import android.util.Log
import com.aashik.music.bluetooth.BluetoothMediaManager
import com.aashik.music.model.AppNotification
import com.aashik.music.notification.AppNotificationManager

class AppNotificationListenerService : NotificationListenerService() {

    companion object {
        private const val TAG = "NotificationListener"
    }

    override fun onListenerConnected() {
        super.onListenerConnected()
        Log.d(TAG, "Notification listener connected")
        AppNotificationManager.setListenerActive(true)
        BluetoothMediaManager.init(applicationContext)
    }

    override fun onListenerDisconnected() {
        super.onListenerDisconnected()
        Log.d(TAG, "Notification listener disconnected")
        AppNotificationManager.setListenerActive(false)
    }

    override fun onNotificationPosted(sbn: StatusBarNotification?) {
        if (sbn == null) return

        val pkg = sbn.packageName ?: return
        // Ignore notifications generated by our own app (e.g. media playback)
        if (pkg == packageName) return

        val notification = sbn.notification ?: return
        val extras = notification.extras ?: return

        val title = extras.getCharSequence(Notification.EXTRA_TITLE)?.toString()?.trim()
        val text = (extras.getCharSequence(Notification.EXTRA_TEXT)
            ?: extras.getCharSequence(Notification.EXTRA_BIG_TEXT)
            ?: extras.getCharSequence(Notification.EXTRA_SUB_TEXT))?.toString()?.trim()

        // Ignore empty / silent technical notifications
        if (title.isNullOrBlank() && text.isNullOrBlank()) return

        val pm = applicationContext.packageManager
        val appName = try {
            val appInfo = pm.getApplicationInfo(pkg, PackageManager.GET_META_DATA)
            pm.getApplicationLabel(appInfo).toString()
        } catch (_: Exception) {
            pkg.substringAfterLast('.')
        }

        // Check if this is a media playback notification (Spotify, YouTube Music, Bluetooth audio, etc.)
        val isMediaStyle = extras.containsKey(Notification.EXTRA_MEDIA_SESSION) ||
                pkg.contains("spotify") || pkg.contains("music") || pkg.contains("youtube") || pkg.contains("audio")

        if (isMediaStyle && !title.isNullOrBlank() && !text.isNullOrBlank()) {
            BluetoothMediaManager.updatePhoneMediaManually(
                title = title,
                artist = text,
                appName = appName,
                isPlaying = true
            )
        }

        val appNotification = AppNotification(
            id = "${sbn.key}_${sbn.postTime}",
            packageName = pkg,
            appName = appName,
            title = title ?: appName,
            text = text ?: "",
            timestamp = sbn.postTime,
            isFromBluetooth = AppNotificationManager.isBluetoothConnected.value,
            category = notification.category
        )

        Log.d(TAG, "Captured notification from $appName: $title - $text")
        AppNotificationManager.postNotification(appNotification)
    }

    override fun onNotificationRemoved(sbn: StatusBarNotification?) {
        // Optional
    }
}
